<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShsxpsp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShsxpsp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerShsxpsp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerShsxpsp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerShsxpsp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Shsxpsp',
    'container.build_id' => '665c527d',
    'container.build_time' => 1607582507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerShsxpsp');
