<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'api_user' => [[], ['_controller' => 'App\\Controller\\ApiUserController::index'], [], [['text', '/api/user']], [], []],
    'api_user_delete' => [['id'], ['_controller' => 'App\\Controller\\ApiUserController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/user-delete']], [], []],
    'api_user_update' => [['id', 'name', 'date', 'address'], ['name' => null, 'date' => null, 'address' => null, '_controller' => 'App\\Controller\\ApiUserController::update'], [], [['variable', '/', '[^/]++', 'address'], ['variable', '/', '[^/]++', 'date'], ['variable', '/', '[^/]++', 'name'], ['variable', '/', '[^/]++', 'id'], ['text', '/api/user-update']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::indexAction'], [], [['text', '/']], [], []],
    'add_inVoice_via_csv' => [[], ['_controller' => 'App\\Controller\\DashboardController::addInvoiceAction'], [], [['text', '/add-invoice']], [], []],
];
